[package]
name = "generate-commits"
version = "0.1.0"
authors = ["Stivenson Rincón <stivenson.rpm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.3.0"
failure = "0.1.0"
run_script = "*"